Here is a matrix that contains the calories of Carbs, Protein and Fats in 100g of different foods.
We need to calculate the percentage of carbs, proteins and fats in each food item without using explicit for loops.
We take the total of each column and store it in a different matrix. We divide each value of the calorie matrix with its corresponding column's total and then multiply the value with 100 to get the percentage.

In [3]:
import numpy as np

# Columns are: Apples, Chicken, Eggs, Potatoes
# Rows are: Carbs, Proteins, Fats
A = np.array([[56.0, 0.0, 4.4, 68.0],
              [1.2, 104.0, 52.0, 8.0],
              [1.8, 135.0, 99.0, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


Now, Calculate the total sum of each column

In [4]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


Now, Percent of carbs, proteins and fats in each food item

In [6]:
percent = 100 * A / cal.reshape(1, 4)
print(percent)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
